import { combineReducers } from "redux"
import {
  roleReducer,
  userReducer,
  parameterReducer,
  couponReducer,
  vendorReducer,
  refundReducer,
  customerReducer,
  prodCategryReducer,
  shiftReducer,
  rowmaterialReducer,
  productPriceReducer,
  productIngredientReducer,
  productOfferReducer,
  productAddtionalReducer,
  productWarehouseLimitReducer,
  productGroupItemReducer,
  orderDetailsReducer,
  puchasedInvoiceReducer,
  puchasedInvoiceLineReducer,
  terminalReducer,
  paymentReasonReducer,
  uomReducer,
  printerReducer,
  paymentMethodReducer,
  taxReducer,
  fAccountReducer,
  payExpeseReducer,
  additionalReducer,
  productionReducer,
  branchReducer,
  floorReducer,
  branchPayMethdReducer,
  tableReducer,
  movementReducer,
  movementLineReducer,
  stockMaintananceeReducer,
  stockMaintananceLineReducer,
  inventoryCountReducer,
  warehouseReducer,
  comboReducer,
  comboOptionReducer,
  comboProductReducer,
  cashupReducer,
  offerReducer,
  packageReducer,
  messageTemplateReducer,
  deliveryPersonReducer,
  screenUpdateReducer,
  transferReducer
} from "./role"

const roleUpdateDateReducers = combineReducers({
  screenUpdate: screenUpdateReducer,
  deliveryPerson: deliveryPersonReducer,
  package: packageReducer,
  role: roleReducer,
  messageTemplate: messageTemplateReducer,
  user: userReducer,
  offer:offerReducer,
  cashup:cashupReducer,
  parameter: parameterReducer,
  transfer:transferReducer,
  coupon: couponReducer,
  orderData: orderDetailsReducer, 
  vendor: vendorReducer,
  refund: refundReducer,
  customer: customerReducer,
  prodCatgry: prodCategryReducer,
  shift: shiftReducer,
  rowmaterial: rowmaterialReducer,
  productPrice: productPriceReducer,
  productIngredient: productIngredientReducer,
  productOffer: productOfferReducer,
  productAddtional: productAddtionalReducer,
  productWarehouseLimit: productWarehouseLimitReducer,
  productGroupItem: productGroupItemReducer,
  puchasedInvoice: puchasedInvoiceReducer,
  puchasedInvoiceLine: puchasedInvoiceLineReducer,
  terminal: terminalReducer,
  paymentReason: paymentReasonReducer,
  uom: uomReducer,
  printer:printerReducer,
  paymentMethod:paymentMethodReducer,
  tax:taxReducer,
  fAccount:fAccountReducer,
  payExpese:payExpeseReducer,
  additional:additionalReducer,
  production:productionReducer,
  branch:branchReducer,
  floor:floorReducer,
  branchPayMethd:branchPayMethdReducer,
  table:tableReducer,
  movement:movementReducer,
  movementLine:movementLineReducer,
  stockMaintanance: stockMaintananceeReducer,
  stockMaintananceLine:stockMaintananceLineReducer,
  inventoryCount:inventoryCountReducer,
  warehouse:warehouseReducer,
  combo:comboReducer,
  comboOption:comboOptionReducer,
  comboProduct:comboProductReducer,
})

export default roleUpdateDateReducers
